[package]
name = "message_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
cron = "0.12.0"
mockall = "0.12.1"
uuid = {version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"]}

[lib]
name = "message_scheduler"
path = "src/lib.rs"

crate-type = ["lib"]
